#!/bin/bash

USE="verity_list -c ... | grep -z ... | blacktar_backup /key/file s3-bucket"

dir=`cd $(dirname $0) && pwd`

passphrase_xxd="`xxd $1`"
bucket="$2"

if [ ! "$tmp" ]; then tmp=/tmp; fi
mkdir "$tmp/$$"

function s3_put { #s3-bucket-name hash path
	echo "put: starting $2 $3" >&2
	hmac=`echo -n "$hash" | "$dir"/../lib/blacktar/hmacs_of_hashes <(echo -n "$passphrase_xxd" | xxd -r) | cut -d ' ' -f 1`
	mkdir "$tmp/$$/$2.d"
	ln -s "$3" "$tmp/$$/$2.d/$2"
#	noise to osbscure file size
#	"$dir"/../lib/blacktar/noise "$3" "$tmp/$$/$2.d/noise"
	( ls "$tmp/$$/$2.d" | tar chCfT "$tmp/$$/$2.d" - - | gpg -c --force-mdc --batch --no-tty --passphrase-fd 3 3< <(echo -n "$passphrase_xxd" | xxd -r) > "$tmp/$$/$hmac" ) 2> "$tmp/$$/err"
	if [ `stat -c%s "$tmp/$$/err"` -ne 0 ]; then
		cat "$tmp/$$/err" >&2
		echo "blacktar put: aborting on tar|gpg error for $2 $3" >&2
		rm -f "$tmp/$$/$hmac"
		rm -rf "$tmp/$$/$2.d"
		return 1; fi
	rm "$tmp/$$/$2.d"/*
	md5=`openssl dgst -md5 -binary "$tmp/$$/$hmac" | openssl enc -base64`
	( gpg --batch --no-tty --passphrase-fd 3 3< <(echo -n "$passphrase_xxd" | xxd -r) < "$tmp/$$/$hmac" | tar xCf "$tmp/$$/$2.d" - ) 2> "$tmp/$$/err"
#	err=`grep -v -e 'gpg: CAST5 encrypted data' -e 'gpg: encrypted with 1 passphrase' -e 'gpg: WARNING: message was not integrity protected' "$tmp/$$/err"`
	err=`grep -v -e 'gpg: CAST5 encrypted data' -e 'gpg: encrypted with 1 passphrase' "$tmp/$$/err"`
	if [ "$err" ]; then
		echo "$err" >&2
		echo "blacktar put: aborting on gpg|tar pipe error for $2 $3" >&2
		rm "$tmp/$$/$hmac"
		rm -rf "$tmp/$$/$2.d"
		return 1; fi 
	if
		[ ! -f "$tmp/$$/$2.d/$2" ]; then
		echo "blacktar verify: missing from archive: $2 ( $3 )" >&2
		rm "$tmp/$$/$hmac"
		rm -rf "$tmp/$$/$2.d"
		return 1; fi
	test_hmac=`sha256sum "$tmp/$$/$2.d/$2" | cut -d ' ' -f 1`
	if
		[ ! "$test_hmac" -o \( "$2" != "$test_hmac" \) ]
		then
			rm -rf "$tmp/$$/$2.d"
			rm "$tmp/$$/$hmac"
			echo "put: aborting on checksum mismatch: $2 $3" 1>&2
			echo "$2"
			return 1; fi

		rm -rf "$tmp/$$/$2.d"
		r=1
		modulus=1
		while [ $r -ne 0 ]; do
			err=$(s3 -u put "$1/$hmac" filename="$tmp/$$/$hmac" md5="$md5" 2>&1 | grep -vE '^[0-9]+ bytes remaining \([0-9]{1,3}% complete\) \.\.\.'; exit ${PIPESTATUS[0]})
			r=$?
			if [ $r -ne 0 ]; then echo "s3 returned $r" >&2; fi
			if [ "$err" ]; then echo "$err" >&2; r=1; fi
			if [ $r -eq 0 ]; then break; fi
			while [ $(($RANDOM%$modulus)) -ne 0 ]; do sleep 60; done
			modulus=$(($modulus+1)); done
		rm "$tmp/$$/$hmac"
		echo "$hmac" >> /var/local/cache/blacktar/"$1"
		echo "put: finished $2 $3" >&2
		echo "$2$3"; }

cat /dev/stdin > "$tmp/$$/stdin-buf"

while IFS= read -r -d '' line; do
	echo ${line:0:64} >> "$tmp/$$/hashes.in"
	echo -n "$line" >> "$tmp/$$/stdin-sorted"
	echo -ne \\0 >> "$tmp/$$/stdin-sorted"
	done < <(sort -uz "$tmp/$$/stdin-buf")

"$dir"/../lib/blacktar/hmacs_of_hashes <(echo -n "$passphrase_xxd" | xxd -r) < "$tmp/$$/hashes.in" | sort -u > "$tmp/$$/hash_lookup_table"
rm "$tmp/$$/hashes.in"
cut -d ' ' -f 1 < "$tmp/$$/hash_lookup_table" > "$tmp/$$/db"

if	[ ! -f "/var/local/cache/blacktar/$bucket" ]
	then	s3_list_keys "$bucket" | sort -u \
		> "/var/local/cache/blacktar/$bucket"; fi

diff "$tmp/$$/db" <(sort -u "/var/local/cache/blacktar/$bucket") | grep '^<' | cut -c 3- | "$dir"/../lib/blacktar/hashes_of_hmacs "$tmp/$$/hash_lookup_table" > "$tmp/$$/diff.hashes"
rm "$tmp/$$/hash_lookup_table" "$tmp/$$/db"
if	[ ! -f "$tmp/$$/diff.hashes" ]
	then rm -rf "$tmp/$$"; exit; fi

while IFS= read -r -d '' line; do
	hash=`echo -n "$line" | cut -c 1-64`
	path=`echo -n "$line" | cut -c 65-`
	s3_put "$bucket" "$hash" "$path"
	done < <("$dir"/../lib/verity/paths "$tmp/$$/stdin-sorted" < "$tmp/$$/diff.hashes")

rm -rf "$tmp/$$"

#IN GOD WE TRVST.
