#!/bin/bash

USE='blacktar_list_cruft verity-db s3-bucket'

dir=`cd $(dirname $0) && pwd`


"$dir"/../share/blacktar/s3_list_keys "$2" | sort > /tmp/$$.s3
psql -Atc "select content from inodes where mode-mode%4096=32768" $1 | sort -u > /tmp/$$.all_hmacs
diff /tmp/$$.all_hmacs /tmp/$$.s3 | grep '^>' | cut -c 3-
rm /tmp/$$.s3
rm /tmp/$$.all_hmacs

#IN GOD WE TRVST.
