#!/bin/bash

modulus=1
while [ true ]; do
	aws s3 ls s3://"$1" --recursive > /tmp/$$.out 2> /tmp/$$.err
	r=$?
	if [ $r -eq 0 -a `stat -c%s /tmp/$$.err` -eq 0 ]; then break; fi
	cat /tmp/$$.err >&2
	while [ $(($RANDOM%$modulus)) -ne 0 ]; do sleep 60; done
	modulus=$(($modulus+1)); done
perl -pe 's/^([^\s]+\s+){3}//' < /tmp/$$.out
rm /tmp/$$.out /tmp/$$.err

#Copyright 2014-2017 Michael Redman
#IN GOD WE TRVST.
